meta_product_name: "naturEscape"
meta_title: "naturEscape - Join a hike and make new buddies"
meta_description: "A web-app to connect likeminded people who share a passion for the outdoors and to help beginners start their hiking journeys"
meta_image: "meta_image.png"
